let { addHistory, getHistory, clearHistory } = require('../model/chatbotHistory');

// Get response message generated by chatbot
// Used by [POST] localhost/api/chatbot/query
const getChatResponse = async (req, res) => {
  // Get input string from user
  const { user_id, user_input } = req.body;

  try {
    // Validate input data
    // Code here ...

    // Send request to API server and get response
    let ai_response = await fetch("http://localhost:8000/ai-model/chatbot/chat", {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        "query": user_input
      })
    });
    let result = await ai_response.json();

    // Validate response data and send corresponding error message
    if (!result.msg) {
      return res.status(400).json({
        error: "An error occured when fetching result from AI server: msg field not found",
        message: result
      });
    }

    // Store chat history to database (use function from imported model)
    // Code here ...
    // addHistory()

    // Return response to user
    return res.status(200).json({
      message: "Success",
      response_text: result.msg
    });
  } catch (error) {
    console.error("Error logging in: ", error);
    return res.status(500).json({
      error: "Internal server error"
    })
  }
}

// Get response message generated by chatbot
// Used by [POST] localhost/api/chatbot/add_urls
const addURL = async (req, res) => {
  // Get input string from user
  const { urls } = req.body;

  try {
    // Validate input data
    if (!urls) {
      return res.status(400).json({
        error: "Invalid input data, urls not found"
      })
    }

    // Send request to API server and get response
    let ai_response = await fetch(`http://localhost:8000/ai-model/chatbot/add_urls?urls=${urls}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      }
      // body: JSON.stringify({
      //   "Input": user_input
      // })
    });
    let result = await ai_response.json();

    // Validate response data and send corresponding error message
    if (!result) {
      return res.status(400).json({
        error: "An error occured when fetching result from AI server"
      });
    }

    // Return response to user
    return res.status(200).json({
      message: "Success",
      result: result
    });
  } catch (error) {
    console.error("Error logging in: ", error);
    return res.status(500).json({
      error: "Internal server error"
    })
  }
}

// Get response message generated by chatbot
// Used by [POST] localhost/api/chatbot/add_pdfs
const addPDF = async (req, res) => {
  // Get input string from user
  const { pdfs } = req.body;

  try {
    // Validate input data
    // if (!req.body) {
    //   return res.status(400).json({
    //     error: "Request body is empty"
    //   })
    // }

    // Send request to API server and get response
    // let ai_response = await fetch(`http://localhost:8000/ai-model/chatbot/add_pdf`, {
    //   method: "POST",
    //   headers: {
    //     "Content-Type": "application/json"
    //   }
    //   // body: JSON.stringify({
    //   //   "Input": user_input
    //   // })
    // });
    // let result = await ai_response.json();

    // Return response to user
    return res.status(200).json({
      message: "Success",
      result: "This is dummy response"
    });
  } catch (error) {
    console.error("Error logging in: ", error);
    return res.status(500).json({
      error: "Internal server error"
    })
  }
}

// Retrieve the saved chat history stored in database
// Used by [POST] localhost/api/chatbot/history
const getChatHistory = async (req, res) => {
  // Get input string from user
  const { user_id } = req.body;

  try {
    // Validate input data
    // Code here ...

    // Get data from database (use function from imported model)
    // Code here ...
    // getHistory()

    // Validate retrieved data and send corresponding error message
    // Code here ...

    // Return response to user
    return res.status(200).json({
      message: `Get history succesful for user ${user_id}`,
      chat_history: []
    });
  } catch (error) {
    console.error("Error logging in: ", error);
    return res.status(500).json({
      error: "Internal server error"
    })
  }
}

// Retrieve the saved chat history stored in database
// Used by [DELETE] localhost/api/chatbot/history
const clearChatHistory = async (req, res) => {
  // Get input string from user
  const { user_id } = req.body;

  try {
    // Validate input data
    // Code here ...

    // Delete data from database (use function from imported model)
    // Code here ...
    // clearHistory()

    // Validate retrieved data and send corresponding error message
    // Code here ...

    // Return response to user
    return res.status(200).json({
      message: `Clear history succesful for user ${user_id}`,
    });
  } catch (error) {
    console.error("Error logging in: ", error);
    return res.status(500).json({
      error: "Internal server error"
    })
  }
}

module.exports = {
  getChatResponse,
  addURL,
  addPDF,
  getChatHistory,
  clearChatHistory
}