// Get response message generated by chatbot
// Used by [POST] localhost/api/obesity/predict
const predict = async (req, res) => {
  // Get input string from user
  // Please refer to the AI_Team_Integration.xlsx for detail information about all input fields
  const user_input = req.body;

  try {
    // Validate input data
    // Code here ...

    // Send request to API server and get response
    // Code here ...

    // Validate response data and send corresponding error message
    // Code here ...

    // Return response to user
    return res.status(200).json({
      message: "Success",
      obesity_level: `Sample obesity level for user ${user_input.user_id}`
    });
  } catch (error) {
    console.error("Error logging in: ", error);
    return res.status(500).json({
      error: "Internal server error"
    })
  }
}

module.exports = {
  predict
}